site_name: "Documentación de Python con explicaciones y ejemplos"

nav:
  - Inicio: index.md
  - Guía de instalación de Python usando visual studio code: guia_de_instalacion/guia_instalacion.md
  - Variables: variables/variables.md
  - Strings: strings/strings.md

theme:
  name: "readthedocs"  

