site_name: "Documentación de Python con explicaciones y ejemplos"

nav:
  - Inicio: index.md
  - Guía de instalación de Python usando visual studio code: guia_de_instalacion/guia_instalacion.md
  - Variables: variables/variables.md
  - Strings: strings/strings.md
  - Tipos de operadores: operadores/operadores.md
  - IF's y Bucles: ifs_y_bucles/ifs_y_bucles.md
  - Funciones: funciones/funciones.md

theme:
  name: "readthedocs"  

